name: Compila per Mac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Questo ti permette di avviarlo anche a mano con un clic

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Scarica il codice dal repository
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Installa le dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compila l'eseguibile per Mac
      run: pyinstaller --onefile --distpath . backend/server.py

    - name: Carica l'eseguibile pronto nei file scaricabili
      uses: actions/upload-artifact@v4
      with:
        name: server-mac
        path: server
